import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../context/AuthContext';
import { jobsApi, vehiclesApi, quotApi } from '../lib/api';
import { useJobUpdates } from '../hooks/useSocket';

const RED='#E40521',DARK='#0A0A0A',CARD='#111111',BORD='#1F1F1F',TEXT='#F9FAFB',TEXT2='#9CA3AF',TEXT3='#4B5563',GREEN='#22C55E',AMBER='#F59E0B',BLUE='#3B82F6';
const STATUS_CONFIG={booking_confirmed:{label:'Booking Confirmed',color:BLUE,bg:'#0A0D1A',step:0},driver_assigned:{label:'Driver Assigned',color:'#8B5CF6',bg:'#0F0A1A',step:1},vehicle_picked_up:{label:'Vehicle Picked Up',color:AMBER,bg:'#1A120A',step:2},inspection_done:{label:'Inspection Done',color:'#F97316',bg:'#1A0F0A',step:3},at_workshop:{label:'At Workshop',color:'#EF4444',bg:'#1A0A0A',step:4},in_progress:{label:'Service in Progress',color:'#F97316',bg:'#1A0F0A',step:5},waiting_approval:{label:'Awaiting Your Approval',color:AMBER,bg:'#1A1A0A',step:6},service_completed:{label:'Service Completed',color:GREEN,bg:'#0A1A0A',step:7},ready_delivery:{label:'Ready for Delivery',color:'#10B981',bg:'#0A1A14',step:8},out_delivery:{label:'Out for Delivery',color:BLUE,bg:'#0A0D1A',step:9},delivered:{label:'Delivered ✓',color:'#6B7280',bg:'#111',step:10}};
const TIMELINE_STEPS=['booking_confirmed','driver_assigned','vehicle_picked_up','inspection_done','at_workshop','in_progress','waiting_approval','service_completed','ready_delivery','out_delivery','delivered'];

function StatusBadge({status}){const cfg=STATUS_CONFIG[status]||{label:status,color:TEXT2,bg:CARD};return(<span style={{display:'inline-flex',alignItems:'center',gap:5,padding:'4px 12px',borderRadius:20,background:cfg.bg,border:`1px solid ${cfg.color}40`,fontSize:12,fontWeight:700,color:cfg.color}}><span style={{width:6,height:6,borderRadius:'50%',background:cfg.color,display:'inline-block'}}/>{cfg.label}</span>);}

function ProgressBar({status}){const cfg=STATUS_CONFIG[status],step=cfg?.step??0,pct=Math.round((step/10)*100);return(<div><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><span style={{fontSize:11,color:TEXT3,fontWeight:700,letterSpacing:'0.08em',textTransform:'uppercase'}}>Service Progress</span><span style={{fontSize:11,color:TEXT2}}>{pct}%</span></div><div style={{height:6,background:'#1A1A1A',borderRadius:3,overflow:'hidden'}}><div style={{height:'100%',width:`${pct}%`,background:`linear-gradient(90deg,${RED},${cfg?.color||RED})`,borderRadius:3,transition:'width 0.5s'}}/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:6}}><span style={{fontSize:10,color:TEXT3}}>Booked</span><span style={{fontSize:10,color:TEXT3}}>Delivered</span></div></div>);}

function TrackingView({job,onRefresh}){
const[quotation,setQuotation]=useState(null),[responding,setResponding]=useState(false);
useEffect(()=>{if(job?.quotation)setQuotation(job.quotation);},[job]);
useJobUpdates(job?.id,{onStatusUpdate:()=>onRefresh(),onQuotation:()=>onRefresh()});
const handleQuotation=async(action)=>{if(!quotation?.id)return;setResponding(true);try{await quotApi.respond(quotation.id,action);onRefresh();}catch(err){alert(err.message);}finally{setResponding(false);}};
if(!job)return(<div style={{textAlign:'center',padding:'60px 20px'}}><div style={{fontSize:40,marginBottom:12}}>🚗</div><div style={{fontSize:16,fontWeight:700,color:TEXT,marginBottom:6}}>No active service</div><div style={{fontSize:13,color:TEXT3}}>Book a service to track your vehicle here</div></div>);
const cfg=STATUS_CONFIG[job.status]||{};
return(<div style={{maxWidth:720,display:'flex',flexDirection:'column',gap:14}}>
<div style={{background:cfg.bg||CARD,border:`1px solid ${cfg.color||BORD}30`,borderRadius:14,padding:'20px 24px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:16,flexWrap:'wrap',gap:10}}><div><div style={{fontFamily:"'DM Mono',monospace",fontSize:11,color:TEXT3,marginBottom:4}}>{job.id}</div><div style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:22,fontWeight:700,color:TEXT}}>{job.year} {job.make} {job.model}</div><div style={{fontSize:12,color:TEXT2}}>{job.plate} · {job.color}</div></div><StatusBadge status={job.status}/></div><ProgressBar status={job.status}/></div>
{job.status==='waiting_approval'&&quotation&&quotation.approval_status==='pending'&&(<div style={{background:'#1A1A0A',border:`2px solid ${AMBER}40`,borderRadius:14,overflow:'hidden'}}><div style={{padding:'14px 20px',borderBottom:`1px solid ${AMBER}20`,display:'flex',alignItems:'center',gap:8}}><span style={{fontSize:16}}>⚠️</span><span style={{fontSize:14,fontWeight:700,color:AMBER}}>Quotation — Approval Required</span></div><div style={{padding:'16px 20px'}}>{quotation.items?.map((item,i)=>(<div key={i} style={{display:'flex',justifyContent:'space-between',padding:'8px 0',borderBottom:`1px solid ${BORD}`,fontSize:13}}><span style={{color:TEXT}}>{item.name}</span><span style={{fontWeight:600,color:item.unit_price===0?GREEN:TEXT}}>{item.unit_price===0?'FREE':`AED ${(item.unit_price*item.quantity).toFixed(0)}`}</span></div>))}<div style={{display:'flex',justifyContent:'space-between',padding:'14px 0 0',marginTop:4,borderTop:`2px solid ${TEXT}`}}><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontWeight:700,fontSize:16,color:TEXT}}>TOTAL</span><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontWeight:700,fontSize:22,color:RED}}>AED {parseFloat(quotation.total_amount).toLocaleString()}</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:14}}><button onClick={()=>handleQuotation('approve')} disabled={responding} style={{padding:'12px',background:GREEN,border:'none',borderRadius:8,fontSize:14,fontWeight:700,color:'#fff',cursor:'pointer',fontFamily:"'Barlow',sans-serif"}}>{responding?'...':'✓ Approve'}</button><button onClick={()=>handleQuotation('decline')} disabled={responding} style={{padding:'12px',background:'#1A0505',border:`1px solid #7F1D1D`,borderRadius:8,fontSize:14,fontWeight:700,color:'#EF4444',cursor:'pointer',fontFamily:"'Barlow',sans-serif"}}>Decline</button></div></div></div>)}
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>
<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:12,padding:'16px 18px'}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:14,letterSpacing:'0.06em'}}>STATUS TIMELINE</div>{TIMELINE_STEPS.map((step,i)=>{const stepIndex=TIMELINE_STEPS.indexOf(job.status),isCompleted=i<=stepIndex,isCurrent=i===stepIndex,scfg=STATUS_CONFIG[step],entry=job.timeline?.find(t=>t.status===step);return(<div key={step} style={{display:'flex',gap:10,marginBottom:0}}><div style={{display:'flex',flexDirection:'column',alignItems:'center',width:14}}><div style={{width:10,height:10,borderRadius:'50%',flexShrink:0,marginTop:3,background:isCompleted?(isCurrent?scfg.color:GREEN):'#2A2A2A',outline:isCurrent?`2px solid ${scfg.color}`:'none',outlineOffset:2}}/>{i<TIMELINE_STEPS.length-1&&<div style={{width:2,flex:1,minHeight:16,background:i<stepIndex?'#22C55E20':'#2A2A2A',margin:'2px 0'}}/>}</div><div style={{paddingBottom:12,flex:1}}><div style={{fontSize:11,fontWeight:isCurrent?700:400,color:isCompleted?TEXT:TEXT3}}>{scfg.label}</div>{entry&&<div style={{fontSize:10,color:TEXT3,fontFamily:"'DM Mono',monospace"}}>{entry.created_at?.slice(0,16)?.replace('T',' ')}</div>}</div></div>);})}</div>
<div style={{display:'flex',flexDirection:'column',gap:12}}>{job.driver_name&&(<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:12,padding:'16px 18px'}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:12,letterSpacing:'0.06em'}}>YOUR DRIVER</div><div style={{display:'flex',alignItems:'center',gap:12,marginBottom:14}}><div style={{width:44,height:44,borderRadius:'50%',background:RED,display:'flex',alignItems:'center',justifyContent:'center',fontSize:18,fontWeight:700,color:'#fff',flexShrink:0}}>{job.driver_name?.[0]}</div><div><div style={{fontSize:14,fontWeight:700,color:TEXT}}>{job.driver_name}</div><div style={{fontSize:12,color:TEXT3}}>{job.driver_phone}</div></div></div><a href={`tel:${job.driver_phone}`} style={{display:'block',textAlign:'center',padding:'10px',background:'#0A1A0A',border:`1px solid #166534`,borderRadius:8,fontSize:13,fontWeight:700,color:GREEN,textDecoration:'none'}}>📞 Call Driver</a></div>)}<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:12,padding:'16px 18px',flex:1}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:10,letterSpacing:'0.06em'}}>SERVICE CENTER</div><div style={{fontSize:13,fontWeight:700,color:TEXT,marginBottom:4}}>{job.service_center_name||'Honda Service Center'}</div>{job.advisor_name&&<div style={{fontSize:12,color:TEXT2}}>Advisor: <span style={{color:TEXT,fontWeight:600}}>{job.advisor_name}</span></div>}</div></div>
</div>
{job.status==='delivered'&&!job.customer_rating&&<RatingCard jobId={job.id} onDone={onRefresh}/>}
{job.customer_rating&&(<div style={{background:'#0A1A0A',border:`1px solid #166534`,borderRadius:12,padding:'16px 18px'}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:8}}>YOUR FEEDBACK</div><div style={{color:AMBER,fontSize:20}}>{'★'.repeat(job.customer_rating)}{'☆'.repeat(5-job.customer_rating)}</div>{job.customer_feedback&&<div style={{fontSize:13,color:TEXT2,marginTop:6,fontStyle:'italic'}}>"{job.customer_feedback}"</div>}</div>)}
</div>);}

function RatingCard({jobId,onDone}){const[rating,setRating]=useState(0),[hover,setHover]=useState(0),[feedback,setFeedback]=useState(''),[loading,setLoading]=useState(false);const submit=async()=>{if(!rating)return alert('Please select a rating');setLoading(true);try{await jobsApi.rate(jobId,{rating,feedback});onDone();}catch(err){alert(err.message);}finally{setLoading(false);}};return(<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:12,padding:'20px 24px'}}><div style={{fontSize:14,fontWeight:700,color:TEXT,marginBottom:4}}>Rate Your Experience</div><div style={{fontSize:12,color:TEXT3,marginBottom:16}}>How was your Honda Door-to-Door service?</div><div style={{display:'flex',gap:8,marginBottom:14}}>{[1,2,3,4,5].map(s=>(<button key={s} onClick={()=>setRating(s)} onMouseOver={()=>setHover(s)} onMouseOut={()=>setHover(0)} style={{fontSize:28,background:'transparent',border:'none',cursor:'pointer',color:s<=(hover||rating)?AMBER:TEXT3,transition:'transform 0.1s',transform:s<=(hover||rating)?'scale(1.2)':'scale(1)'}}>★</button>))}</div><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Tell us about your experience..." rows={3} style={{width:'100%',padding:'10px 12px',background:'#1A1A1A',border:`1px solid ${BORD}`,borderRadius:8,fontSize:13,color:TEXT,fontFamily:"'Barlow',sans-serif",resize:'vertical',marginBottom:12,boxSizing:'border-box'}}/><button onClick={submit} disabled={loading||!rating} style={{width:'100%',padding:'12px',background:rating?RED:'#2A2A2A',border:'none',borderRadius:8,fontSize:14,fontWeight:700,color:rating?'#fff':TEXT3,cursor:rating?'pointer':'not-allowed',fontFamily:"'Barlow',sans-serif"}}>{loading?'Submitting...':'Submit Rating'}</button></div>);}

function BookingForm({vehicles,onBooked}){const[form,setForm]=useState({vehicle_id:'',service_type:'',pickup_address:'',scheduled_pickup_at:'',notes:''}),[loading,setLoading]=useState(false);const set=(k,v)=>setForm(f=>({...f,[k]:v}));const submit=async()=>{if(!form.vehicle_id||!form.service_type||!form.pickup_address)return alert('Please fill all required fields');setLoading(true);try{await jobsApi.create(form);onBooked();}catch(err){alert(err.message);}finally{setLoading(false);}};const SERVICE_TYPES=['30,000 km Service','60,000 km Service','AC Service','Tire Service','Battery Replacement','Brake Service','General Inspection','Oil Change'];return(<div style={{maxWidth:560}}><div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:14,padding:'24px'}}><div style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:20,fontWeight:700,color:TEXT,marginBottom:20}}>Book Door-to-Door Service</div>{[{label:'Vehicle *',key:'vehicle_id',type:'select',opts:vehicles.map(v=>({value:v.id,label:`${v.year} ${v.model} – ${v.plate}`}))},{label:'Service Type *',key:'service_type',type:'select',opts:SERVICE_TYPES.map(s=>({value:s,label:s}))},{label:'Pickup Address *',key:'pickup_address',type:'text',ph:'Your full address'},{label:'Preferred Date & Time',key:'scheduled_pickup_at',type:'datetime-local'},{label:'Additional Notes',key:'notes',type:'textarea',ph:'Any special requests...'}].map(f=>(<div key={f.key} style={{marginBottom:16}}><label style={{display:'block',fontSize:11,fontWeight:700,color:TEXT3,letterSpacing:'0.08em',textTransform:'uppercase',marginBottom:8}}>{f.label}</label>{f.type==='select'?(<select value={form[f.key]} onChange={e=>set(f.key,e.target.value)} style={{width:'100%',padding:'11px 14px',background:'#1A1A1A',border:`1px solid ${BORD}`,borderRadius:8,fontSize:13,color:form[f.key]?TEXT:TEXT3,fontFamily:"'Barlow',sans-serif"}}><option value="">Select...</option>{f.opts.map(o=>(<option key={o.value} value={o.value}>{o.label}</option>))}</select>):f.type==='textarea'?(<textarea rows={3} value={form[f.key]} onChange={e=>set(f.key,e.target.value)} placeholder={f.ph} style={{width:'100%',padding:'11px 14px',background:'#1A1A1A',border:`1px solid ${BORD}`,borderRadius:8,fontSize:13,color:TEXT,fontFamily:"'Barlow',sans-serif",resize:'vertical',boxSizing:'border-box'}}/>):(<input type={f.type||'text'} value={form[f.key]} onChange={e=>set(f.key,e.target.value)} placeholder={f.ph} style={{width:'100%',padding:'11px 14px',background:'#1A1A1A',border:`1px solid ${BORD}`,borderRadius:8,fontSize:13,color:TEXT,fontFamily:"'Barlow',sans-serif"}}/>)}</div>))}<button onClick={submit} disabled={loading} style={{width:'100%',padding:'13px',background:loading?'#7F0010':RED,border:'none',borderRadius:8,fontSize:14,fontWeight:700,color:'#fff',cursor:loading?'not-allowed':'pointer',fontFamily:"'Barlow',sans-serif",marginTop:4}}>{loading?'Booking...':'Confirm Booking →'}</button></div></div>);}

function HistoryList({jobs,onSelect}){if(!jobs.length)return(<div style={{textAlign:'center',padding:'60px 20px'}}><div style={{fontSize:40,marginBottom:12}}>📋</div><div style={{fontSize:14,color:TEXT3}}>No service history yet</div></div>);return(<div style={{maxWidth:720,display:'flex',flexDirection:'column',gap:10}}>{jobs.map(job=>(<div key={job.id} onClick={()=>onSelect(job)} style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:12,padding:'16px 20px',cursor:'pointer',display:'flex',alignItems:'center',gap:16}} onMouseOver={e=>e.currentTarget.style.borderColor='#2A2A2A'} onMouseOut={e=>e.currentTarget.style.borderColor=BORD}><div style={{flex:1}}><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:4}}><span style={{fontFamily:"'DM Mono',monospace",fontSize:11,color:RED,fontWeight:700}}>{job.id}</span><StatusBadge status={job.status}/></div><div style={{fontSize:14,fontWeight:700,color:TEXT}}>{job.service_type}</div><div style={{fontSize:12,color:TEXT3,marginTop:2}}>{job.year} {job.model} · {job.created_at?.slice(0,10)}</div></div>{job.total_amount&&(<div style={{textAlign:'right'}}><div style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:20,fontWeight:700,color:TEXT}}>AED {parseFloat(job.total_amount).toLocaleString()}</div>{job.customer_rating&&<div style={{color:AMBER,fontSize:12}}>{'★'.repeat(job.customer_rating)}</div>}</div>)}<div style={{fontSize:18,color:TEXT3}}>›</div></div>))}</div>);}

export default function CustomerPortal(){
const{user,logout}=useAuth();
const[tab,setTab]=useState('track'),[jobs,setJobs]=useState([]),[vehicles,setVehicles]=useState([]),[loading,setLoading]=useState(true),[selectedJob,setSelectedJob]=useState(null);
const load=useCallback(async()=>{try{const[jobsRes,vehs]=await Promise.all([jobsApi.list({limit:20}),vehiclesApi.list()]);const allJobs=jobsRes.jobs||[];setJobs(allJobs);setVehicles(vehs);const active=allJobs.find(j=>j.status!=='delivered');if(active){const full=await jobsApi.get(active.id);setSelectedJob(full);}}catch(err){console.error(err);}finally{setLoading(false);}},[ ]);
useEffect(()=>{load();},[]);
const handleSelectJob=async(job)=>{try{const full=await jobsApi.get(job.id);setSelectedJob(full);setTab('track');}catch(err){console.error(err);}};
return(<div style={{background:DARK,minHeight:'100vh',fontFamily:"'Barlow',sans-serif",display:'flex',flexDirection:'column'}}>
<div style={{background:'#0D0D0D',borderBottom:`1px solid ${BORD}`,padding:'0 24px',display:'flex',alignItems:'center',justifyContent:'space-between',height:60,flexShrink:0}}><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{background:RED,borderRadius:6,padding:'4px 10px'}}><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontWeight:800,fontSize:16,color:'#fff',letterSpacing:'0.06em'}}>HONDA</span></div><div><div style={{fontSize:13,fontWeight:700,color:TEXT}}>{user?.name}</div><div style={{fontSize:10,color:TEXT3}}>My Honda Service</div></div></div><button onClick={logout} style={{background:'transparent',border:`1px solid ${BORD}`,borderRadius:8,padding:'6px 12px',color:TEXT3,cursor:'pointer',fontSize:12}}>Sign Out</button></div>
<div style={{display:'flex',borderBottom:`1px solid ${BORD}`,background:'#0D0D0D',padding:'0 24px'}}>{[['track','Track Vehicle'],['book','Book Service'],['history','History']].map(([k,l])=>(<button key={k} onClick={()=>setTab(k)} style={{padding:'14px 18px',fontSize:13,fontWeight:700,cursor:'pointer',border:'none',background:'transparent',color:tab===k?RED:TEXT3,borderBottom:tab===k?`2px solid ${RED}`:'2px solid transparent'}}>{l}</button>))}</div>
<div style={{flex:1,overflowY:'auto',padding:24}}>{loading?(<div style={{textAlign:'center',padding:'60px',color:TEXT3}}>Loading...</div>):(<>{tab==='track'&&<TrackingView job={selectedJob} onRefresh={load}/>}{tab==='book'&&<BookingForm vehicles={vehicles} onBooked={()=>{load();setTab('track');}}/>}{tab==='history'&&<HistoryList jobs={jobs} onSelect={handleSelectJob}/>}</>)}</div>
</div>);}
