import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../context/AuthContext';
import { jobsApi, driversApi, notiApi } from '../lib/api';
import { useSocket } from '../hooks/useSocket';
import QuotationBuilder from '../components/QuotationBuilder';
import Reports from './Reports';
import Admin from './Admin';
import LiveTracking from '../components/LiveTracking';

const RED='#E40521',DARK='#0A0A0A',CARD='#111111',BORD='#1F1F1F',TEXT='#F9FAFB',TEXT2='#9CA3AF',TEXT3='#4B5563',GREEN='#22C55E',AMBER='#F59E0B',BLUE='#3B82F6',BG='#0D0D0D';

const STATUS_CONFIG={booking_confirmed:{label:'Booking Confirmed',color:BLUE,bg:'#0A0D1A'},driver_assigned:{label:'Driver Assigned',color:'#8B5CF6',bg:'#0F0A1A'},vehicle_picked_up:{label:'Vehicle Picked Up',color:AMBER,bg:'#1A120A'},inspection_done:{label:'Inspection Done',color:'#F97316',bg:'#1A0F0A'},at_workshop:{label:'At Workshop',color:'#EF4444',bg:'#1A0A0A'},in_progress:{label:'In Progress',color:'#F97316',bg:'#1A0F0A'},waiting_approval:{label:'Awaiting Approval',color:AMBER,bg:'#1A1A0A'},service_completed:{label:'Service Completed',color:GREEN,bg:'#0A1A0A'},ready_delivery:{label:'Ready for Delivery',color:'#10B981',bg:'#0A1A14'},out_delivery:{label:'Out for Delivery',color:BLUE,bg:'#0A0D1A'},delivered:{label:'Delivered',color:'#6B7280',bg:'#111'}};
const TIMELINE_STEPS=['booking_confirmed','driver_assigned','vehicle_picked_up','inspection_done','at_workshop','in_progress','waiting_approval','service_completed','ready_delivery','out_delivery','delivered'];
const STATUS_NEXT={booking_confirmed:['driver_assigned'],driver_assigned:['vehicle_picked_up'],vehicle_picked_up:['inspection_done'],inspection_done:['at_workshop'],at_workshop:['in_progress'],in_progress:['waiting_approval','service_completed'],waiting_approval:['service_completed'],service_completed:['ready_delivery'],ready_delivery:['out_delivery'],out_delivery:['delivered'],delivered:[]};

function StatusBadge({status}){const cfg=STATUS_CONFIG[status]||{label:status,color:TEXT2,bg:CARD};return(<span style={{display:'inline-flex',alignItems:'center',gap:5,padding:'3px 10px',borderRadius:20,background:cfg.bg,border:`1px solid ${cfg.color}30`,fontSize:11,fontWeight:700,color:cfg.color,whiteSpace:'nowrap'}}><span style={{width:5,height:5,borderRadius:'50%',background:cfg.color,display:'inline-block'}}/>{cfg.label}</span>);}

function KpiCard({label,value,sub,color}){return(<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:12,padding:'18px 20px',borderLeft:`3px solid ${color}`}}><div style={{fontSize:10,fontWeight:700,color:TEXT3,letterSpacing:'0.1em',textTransform:'uppercase',marginBottom:10}}>{label}</div><div style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:38,fontWeight:700,color:TEXT,lineHeight:1}}>{value}</div>{sub&&<div style={{fontSize:11,color:TEXT3,marginTop:6}}>{sub}</div>}</div>);}

function JobTimeline({job}){const stepIndex=TIMELINE_STEPS.indexOf(job.status);return(<div>{TIMELINE_STEPS.map((step,i)=>{const isCompleted=i<=stepIndex,isCurrent=i===stepIndex,cfg=STATUS_CONFIG[step],entry=job.timeline?.find(t=>t.status===step);return(<div key={step} style={{display:'flex',gap:12}}><div style={{display:'flex',flexDirection:'column',alignItems:'center',width:16}}><div style={{width:12,height:12,borderRadius:'50%',flexShrink:0,marginTop:4,background:isCompleted?(isCurrent?cfg.color:GREEN):'#2A2A2A',outline:isCurrent?`2px solid ${cfg.color}`:'none',outlineOffset:2}}/>{i<TIMELINE_STEPS.length-1&&<div style={{width:2,flex:1,minHeight:20,background:i<stepIndex?'#22C55E30':'#2A2A2A',margin:'3px 0'}}/>}</div><div style={{paddingBottom:16,flex:1}}><div style={{display:'flex',alignItems:'center',gap:8}}><span style={{fontSize:12,fontWeight:isCurrent?700:400,color:isCompleted?TEXT:TEXT3}}>{cfg.label}</span>{isCurrent&&<span style={{fontSize:9,background:cfg.bg,color:cfg.color,padding:'1px 6px',borderRadius:8,fontWeight:800,border:`1px solid ${cfg.color}40`}}>NOW</span>}</div>{entry&&<div style={{fontSize:11,color:TEXT3,marginTop:2,fontFamily:"'DM Mono',monospace"}}>{entry.note||entry.created_at?.slice(0,16)?.replace('T',' ')}</div>}</div></div>);})}</div>);}

function JobDrawer({job,drivers,onClose,onRefresh}){
const[tab,setTab]=useState('timeline'),[updating,setUpdating]=useState(false),[selectedDriver,setSelectedDriver]=useState(''),[note,setNote]=useState(''),[showQuotBuilder,setShowQuotBuilder]=useState(false);
const nextStatuses=STATUS_NEXT[job?.status]||[];
const handleStatusUpdate=async(newStatus)=>{setUpdating(true);try{await jobsApi.updateStatus(job.id,{status:newStatus,note});onRefresh();onClose();}catch(err){alert(err.message);}finally{setUpdating(false);}};
const handleAssignDriver=async()=>{if(!selectedDriver)return alert('Select a driver');setUpdating(true);try{await jobsApi.assignDriver(job.id,{driver_id:selectedDriver});onRefresh();onClose();}catch(err){alert(err.message);}finally{setUpdating(false);}};
if(!job)return null;
return(<><div onClick={onClose} style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.7)',zIndex:99}}/>
<div style={{position:'fixed',top:0,right:0,bottom:0,width:480,background:'#111',borderLeft:`1px solid ${BORD}`,zIndex:100,display:'flex',flexDirection:'column'}}>
<div style={{padding:'20px 24px',borderBottom:`1px solid ${BORD}`,display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}>
<div><div style={{fontFamily:"'DM Mono',monospace",fontSize:11,color:TEXT3,marginBottom:4}}>{job.id}</div><div style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:22,fontWeight:700,color:TEXT}}>{job.customer_name}</div><div style={{fontSize:12,color:TEXT2,marginTop:2}}>{job.year} {job.make} {job.model} · {job.plate}</div><div style={{marginTop:8}}><StatusBadge status={job.status}/></div></div>
<button onClick={onClose} style={{background:'transparent',border:'none',color:TEXT3,cursor:'pointer',fontSize:20}}>✕</button></div>
<div style={{display:'flex',borderBottom:`1px solid ${BORD}`,padding:'0 24px'}}>{['timeline','details','actions'].map(t=>(<button key={t} onClick={()=>setTab(t)} style={{padding:'12px 14px',fontSize:12,fontWeight:700,cursor:'pointer',color:tab===t?RED:TEXT3,background:'transparent',border:'none',borderBottom:tab===t?`2px solid ${RED}`:'2px solid transparent',textTransform:'capitalize'}}>{t}</button>))}</div>
<div style={{flex:1,overflowY:'auto',padding:'20px 24px'}}>
{tab==='timeline'&&<JobTimeline job={job}/>}
{tab==='details'&&(<div style={{display:'grid',gap:12}}><div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:10,padding:'16px 18px',display:'grid',gridTemplateColumns:'1fr 1fr',gap:'12px 20px'}}>{[['Service Type',job.service_type],['Date',job.scheduled_pickup_at?.slice(0,10)||'—'],['Driver',job.driver_name||'Not assigned'],['Advisor',job.advisor_name||'—'],['Service Center',job.service_center_name||'—'],['Customer Phone',job.customer_phone],['Pickup Address',job.pickup_address],['Customer Email',job.customer_email]].map(([l,v])=>(<div key={l} style={{gridColumn:['Pickup Address','Customer Email'].includes(l)?'1/-1':'auto'}}><div style={{fontSize:10,fontWeight:700,color:TEXT3,letterSpacing:'0.08em',textTransform:'uppercase',marginBottom:3}}>{l}</div><div style={{fontSize:13,color:TEXT}}>{v}</div></div>))}</div>{job.total_amount&&(<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:10}}>QUOTATION</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:13,color:TEXT}}>Total</span><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:22,fontWeight:700,color:RED}}>AED {parseFloat(job.total_amount||0).toLocaleString()}</span></div><div style={{marginTop:8}}><span style={{fontSize:11,padding:'2px 8px',borderRadius:10,background:job.quotation_status==='approved'?'#0A1A0A':'#1A1A0A',color:job.quotation_status==='approved'?GREEN:AMBER,fontWeight:700}}>{(job.quotation_status||'pending').toUpperCase()}</span></div></div>)}{job.customer_rating&&(<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:8}}>CUSTOMER FEEDBACK</div><div style={{color:AMBER,fontSize:16,marginBottom:6}}>{'★'.repeat(job.customer_rating)}{'☆'.repeat(5-job.customer_rating)}</div>{job.customer_feedback&&<div style={{fontSize:13,color:TEXT2,fontStyle:'italic'}}>"{job.customer_feedback}"</div>}</div>)}</div>)}
{tab==='actions'&&(<div style={{display:'flex',flexDirection:'column',gap:14}}>
{job.status==='booking_confirmed'&&(<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:12}}>ASSIGN DRIVER</div><select value={selectedDriver} onChange={e=>setSelectedDriver(e.target.value)} style={{width:'100%',padding:'10px 12px',background:'#1A1A1A',border:`1px solid ${BORD}`,borderRadius:8,fontSize:13,color:TEXT,marginBottom:10,fontFamily:"'Barlow',sans-serif"}}><option value="">Select a driver...</option>{drivers.map(d=>(<option key={d.id} value={d.id}>{d.name} ({d.active_jobs} active)</option>))}</select><button onClick={handleAssignDriver} disabled={updating} style={{width:'100%',padding:'11px',background:RED,border:'none',borderRadius:8,fontSize:13,fontWeight:700,color:'#fff',cursor:'pointer',fontFamily:"'Barlow',sans-serif"}}>{updating?'Assigning...':'Assign Driver'}</button></div>)}
<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:12}}>QUOTATION</div><button onClick={()=>setShowQuotBuilder(true)} style={{width:'100%',padding:'11px',background:'#0A1A0A',border:`1px solid #166534`,borderRadius:8,fontSize:13,fontWeight:700,color:GREEN,cursor:'pointer',fontFamily:"'Barlow',sans-serif"}}>📋 Build & Send Quotation</button></div>
{nextStatuses.length>0&&(<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:12,fontWeight:700,color:TEXT2,marginBottom:12}}>UPDATE STATUS</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note (optional)..." rows={2} style={{width:'100%',padding:'10px 12px',background:'#1A1A1A',border:`1px solid ${BORD}`,borderRadius:8,fontSize:13,color:TEXT,marginBottom:10,fontFamily:"'Barlow',sans-serif",resize:'vertical'}}/>{nextStatuses.map(s=>{const cfg=STATUS_CONFIG[s];return(<button key={s} onClick={()=>handleStatusUpdate(s)} disabled={updating} style={{width:'100%',padding:'11px',background:cfg.bg,border:`1px solid ${cfg.color}50`,borderRadius:8,fontSize:13,fontWeight:700,color:cfg.color,cursor:'pointer',fontFamily:"'Barlow',sans-serif",marginBottom:8}}>{updating?'Updating...':`→ ${cfg.label}`}</button>);})}</div>)}
</div>)}
</div></div>
{showQuotBuilder&&<QuotationBuilder jobId={job.id} jobInfo={job} onClose={()=>setShowQuotBuilder(false)} onSaved={()=>{onRefresh();onClose();}}/>}
</>);}

export default function Dashboard(){
const{user,logout}=useAuth();
const[jobs,setJobs]=useState([]),[stats,setStats]=useState({}),[drivers,setDrivers]=useState([]),[loading,setLoading]=useState(true),[selectedJob,setSelectedJob]=useState(null),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[notifs,setNotifs]=useState([]),[showNotifs,setShowNotifs]=useState(false),[showReports,setShowReports]=useState(false),[showAdmin,setShowAdmin]=useState(false),[showMap,setShowMap]=useState(false);
const load=useCallback(async()=>{try{const params={};if(filter!=='all')params.status=filter;if(search)params.search=search;const[jobsRes,statsRes,driversRes,notiRes]=await Promise.all([jobsApi.list(params),jobsApi.stats(),driversApi.list(),notiApi.list()]);setJobs(jobsRes.jobs||[]);setStats(statsRes);setDrivers(driversRes);setNotifs(notiRes.notifications||[]);}catch(err){console.error(err);}finally{setLoading(false);}},[ filter,search]);
useEffect(()=>{load();},[load]);
useSocket({'job:new':()=>load(),'job:status_update':()=>load(),'quotation:response':()=>load()});
const openJob=async(job)=>{try{const full=await jobsApi.get(job.id);setSelectedJob(full);}catch(err){console.error(err);}};
const FILTERS=[{id:'all',label:'All',count:jobs.length},{id:'booking_confirmed',label:'New',count:jobs.filter(j=>j.status==='booking_confirmed').length},{id:'waiting_approval',label:'Approval',count:jobs.filter(j=>j.status==='waiting_approval').length},{id:'ready_delivery',label:'Delivery',count:jobs.filter(j=>j.status==='ready_delivery').length},{id:'delivered',label:'Done',count:jobs.filter(j=>j.status==='delivered').length}];
const unreadCount=notifs.filter(n=>!n.is_read).length;

if(showAdmin) return(
  <div style={{background:BG,minHeight:'100vh',fontFamily:"'Barlow',sans-serif",display:'flex',flexDirection:'column'}}>
    <div style={{background:DARK,borderBottom:`1px solid ${BORD}`,padding:'0 28px',display:'flex',alignItems:'center',justifyContent:'space-between',height:60,flexShrink:0}}>
      <div style={{display:'flex',alignItems:'center',gap:14}}><div style={{background:RED,borderRadius:6,padding:'4px 10px'}}><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontWeight:800,fontSize:16,color:'#fff',letterSpacing:'0.06em'}}>HONDA</span></div><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:14,fontWeight:600,color:TEXT3,letterSpacing:'0.08em'}}>SERVICE OPS</span></div>
      <button onClick={logout} style={{background:'transparent',border:`1px solid ${BORD}`,borderRadius:8,padding:'6px 12px',color:TEXT3,cursor:'pointer',fontSize:12}}>Sign Out</button>
    </div>
    <Admin onBack={()=>setShowAdmin(false)}/>
  </div>
);

if(showMap) return <LiveTracking onClose={()=>setShowMap(false)}/>;

if(showReports) return(
  <div style={{background:BG,minHeight:'100vh',fontFamily:"'Barlow',sans-serif",display:'flex',flexDirection:'column'}}>
    <div style={{background:DARK,borderBottom:`1px solid ${BORD}`,padding:'0 28px',display:'flex',alignItems:'center',justifyContent:'space-between',height:60,flexShrink:0}}>
      <div style={{display:'flex',alignItems:'center',gap:14}}><div style={{background:RED,borderRadius:6,padding:'4px 10px'}}><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontWeight:800,fontSize:16,color:'#fff',letterSpacing:'0.06em'}}>HONDA</span></div><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:14,fontWeight:600,color:TEXT3,letterSpacing:'0.08em'}}>SERVICE OPS</span></div>
      <button onClick={logout} style={{background:'transparent',border:`1px solid ${BORD}`,borderRadius:8,padding:'6px 12px',color:TEXT3,cursor:'pointer',fontSize:12}}>Sign Out</button>
    </div>
    <Reports onBack={()=>setShowReports(false)}/>
  </div>
);

return(<div style={{background:BG,minHeight:'100vh',fontFamily:"'Barlow',sans-serif",display:'flex',flexDirection:'column'}}>
<div style={{background:DARK,borderBottom:`1px solid ${BORD}`,padding:'0 28px',display:'flex',alignItems:'center',justifyContent:'space-between',height:60,flexShrink:0}}>
<div style={{display:'flex',alignItems:'center',gap:14}}><div style={{background:RED,borderRadius:6,padding:'4px 10px'}}><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontWeight:800,fontSize:16,color:'#fff',letterSpacing:'0.06em'}}>HONDA</span></div><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:14,fontWeight:600,color:TEXT3,letterSpacing:'0.08em'}}>SERVICE OPS</span></div>
<div style={{display:'flex',alignItems:'center',gap:12}}>
<button onClick={()=>setShowReports(true)} style={{background:'transparent',border:`1px solid ${BORD}`,borderRadius:8,padding:'7px 14px',color:TEXT2,cursor:'pointer',fontSize:12,fontWeight:700}}>📊 Reports</button>
<button onClick={()=>setShowAdmin(true)} style={{background:'transparent',border:`1px solid ${BORD}`,borderRadius:8,padding:'7px 14px',color:TEXT2,cursor:'pointer',fontSize:12,fontWeight:700}}>👥 Users</button>
<button onClick={()=>setShowMap(true)} style={{background:'transparent',border:`1px solid ${BORD}`,borderRadius:8,padding:'7px 14px',color:TEXT2,cursor:'pointer',fontSize:12,fontWeight:700}}>🗺️ Live Map</button>
<div style={{position:'relative'}}><button onClick={()=>setShowNotifs(!showNotifs)} style={{background:'transparent',border:`1px solid ${BORD}`,borderRadius:8,padding:'6px 12px',color:TEXT2,cursor:'pointer',fontSize:13,display:'flex',alignItems:'center',gap:6}}>🔔{unreadCount>0&&<span style={{background:RED,color:'#fff',fontSize:9,padding:'1px 5px',borderRadius:10,fontWeight:800}}>{unreadCount}</span>}</button>{showNotifs&&(<div style={{position:'absolute',right:0,top:40,width:300,background:'#111',border:`1px solid ${BORD}`,borderRadius:12,zIndex:200,maxHeight:360,overflowY:'auto'}}><div style={{padding:'12px 16px',borderBottom:`1px solid ${BORD}`,fontSize:13,fontWeight:700,color:TEXT}}>Notifications</div>{notifs.slice(0,8).map(n=>(<div key={n.id} style={{padding:'12px 16px',borderBottom:`1px solid ${BORD}`,background:n.is_read?'transparent':'#0A0D1A'}}><div style={{fontSize:12,fontWeight:700,color:TEXT}}>{n.title}</div><div style={{fontSize:11,color:TEXT2,marginTop:2}}>{n.body}</div></div>))}{notifs.length===0&&<div style={{padding:'20px',textAlign:'center',fontSize:13,color:TEXT3}}>No notifications</div>}</div>)}</div>
<div style={{fontSize:13,color:TEXT2}}>{user?.name}</div>
<button onClick={logout} style={{background:'transparent',border:`1px solid ${BORD}`,borderRadius:8,padding:'6px 12px',color:TEXT3,cursor:'pointer',fontSize:12}}>Sign Out</button>
</div></div>
<div style={{flex:1,overflow:'hidden',display:'flex',flexDirection:'column',padding:'24px 28px'}}>
<div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',marginBottom:20}}><div><div style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:28,fontWeight:700,color:TEXT}}>Operations Dashboard</div><div style={{fontSize:13,color:TEXT3,marginTop:2}}>{new Date().toLocaleDateString('en-AE',{weekday:'long',year:'numeric',month:'long',day:'numeric'})}</div></div></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:12,marginBottom:24}}><KpiCard label="Total Jobs" value={stats.total||0} sub="All time" color={BLUE}/><KpiCard label="Active" value={stats.active||0} sub="In progress" color={AMBER}/><KpiCard label="Awaiting Approval" value={stats.awaiting_approval||0} sub="Needs action" color={RED}/><KpiCard label="Ready Delivery" value={stats.ready_delivery||0} sub="To deliver" color={GREEN}/><KpiCard label="Avg Rating" value={stats.avg_rating||'—'} sub={`${stats.completed||0} done`} color='#8B5CF6'/></div>
<div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center'}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search jobs, customers, plates..." style={{flex:1,padding:'10px 14px',background:CARD,border:`1px solid ${BORD}`,borderRadius:8,fontSize:13,color:TEXT,fontFamily:"'Barlow',sans-serif"}}/><div style={{display:'flex',background:CARD,border:`1px solid ${BORD}`,borderRadius:8,overflow:'hidden'}}>{FILTERS.map(f=>(<button key={f.id} onClick={()=>setFilter(f.id)} style={{padding:'10px 12px',fontSize:11,fontWeight:700,cursor:'pointer',border:'none',background:filter===f.id?RED:'transparent',color:filter===f.id?'#fff':TEXT3}}>{f.label} {f.count}</button>))}</div></div>
<div style={{flex:1,overflowY:'auto'}}><div style={{display:'grid',gridTemplateColumns:'150px 1fr 130px 170px 100px 40px',padding:'8px 16px',gap:12,marginBottom:4}}>{['Job ID','Customer / Vehicle','Service','Status','Date',''].map(h=>(<div key={h} style={{fontSize:10,fontWeight:700,color:TEXT3,letterSpacing:'0.08em',textTransform:'uppercase'}}>{h}</div>))}</div>
<div style={{background:CARD,border:`1px solid ${BORD}`,borderRadius:12,overflow:'hidden'}}>{loading?(<div style={{padding:'40px',textAlign:'center',color:TEXT3}}>Loading...</div>):jobs.length===0?(<div style={{padding:'60px',textAlign:'center',color:TEXT3}}>No jobs found</div>):jobs.map((job,i)=>(<div key={job.id} onClick={()=>openJob(job)} style={{display:'grid',gridTemplateColumns:'150px 1fr 130px 170px 100px 40px',padding:'14px 16px',gap:12,alignItems:'center',borderBottom:i<jobs.length-1?`1px solid ${BORD}`:'none',cursor:'pointer'}} onMouseOver={e=>e.currentTarget.style.background='#161616'} onMouseOut={e=>e.currentTarget.style.background='transparent'}><div style={{fontFamily:"'DM Mono',monospace",fontSize:11,color:RED,fontWeight:700}}>{job.id}</div><div><div style={{fontSize:13,fontWeight:700,color:TEXT}}>{job.customer_name}</div><div style={{fontSize:11,color:TEXT3}}>{job.year} {job.model} · {job.plate}</div></div><div style={{fontSize:12,color:TEXT2}}>{job.service_type?.slice(0,18)}</div><div><StatusBadge status={job.status}/></div><div style={{fontSize:11,color:TEXT3,fontFamily:"'DM Mono',monospace"}}>{job.created_at?.slice(0,10)}</div><div style={{fontSize:18,color:TEXT3,textAlign:'center'}}>›</div></div>))}</div></div></div>
{selectedJob&&<JobDrawer job={selectedJob} drivers={drivers} onClose={()=>setSelectedJob(null)} onRefresh={load}/>}
</div>);}
